version: '3'
services:
    database:
        image: 'postgres' # use latest official postgres version
        env_file:
            - .env # configure postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/ # persist data even if container shuts down
            - ./postgresql.conf:/etc/postgresql.conf
        ports:
            - '5432:5432'
        command: postgres -c config_file=/etc/postgresql.conf
# volumes:
#     database-data: # named volumes can be managed easier using docker-compose
